ERROR - 2022-12-11 20:05:58 --> Error connecting to the database: Error: Call to undefined function CodeIgniter\Database\Postgre\pg_connect() in D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:69
Stack trace:
#0 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\Postgre\Connection->connect(false)
#1 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#3 D:\xampp\htdocs\pos\app\Models\login_m.php(53): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\pos\app\Controllers\utama.php(32): App\Models\login_m->index()
#5 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\utama->login()
#6 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
#7 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\pos\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-12-11 20:05:58 --> Unable to connect to the database.
Main connection [postgre]: Call to undefined function CodeIgniter\Database\Postgre\pg_connect()
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "user"
LEFT JOIN "contact" ON "contact"."contact_id"="user"."contact_id"
LEFT JOIN "branch" ON "branch"."branch_id"="user"."branch_id"
LEFT JOIN "permission_group" ON "permission_group"."permission_group_id"="user"."permission_group_id"
LEFT JOIN "permission" ON "permission"."permission_group_id"="user"."permission_group_id"
LEFT JOIN "modul" ON "modul"."modul_id"="permission"."modul_id"
LEFT JOIN "modul_group" ON "modul_group"."modul_group_id"="modul"."modul_group_id"
WHERE "username" = :username:
AND   (
"modul_group_name" = :modul_group_name:
OR "modul_group_name" = :modul_group_name.1:
OR "modul_group_name" = :modul_group_name.2:
OR "modul_group_name" = :modul_group_name.3:
OR "modul_group_name" = :modul_group_name.4:
OR "modul_group_name" = :modul_group_name.5:
OR "modul_group_name" = :modul_group_name.6:
OR "modul_group_name" = :modul_group_name.7:
OR "modul_group_name" = :modul_group_name.8:
 )', [...], false)
 3 APPPATH\Models\login_m.php(53): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\utama.php(32): App\Models\login_m->index()
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\utama->login()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-11 20:11:24 --> Error connecting to the database: ErrorException: mysqli::real_connect(): Error while reading greeting packet. PID=27876 in D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'D:\\xampp\\htdocs...', 171)
#1 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'pos', 5432, '', 0)
#2 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#4 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 D:\xampp\htdocs\pos\app\Models\login_m.php(53): CodeIgniter\Database\BaseBuilder->get()
#6 D:\xampp\htdocs\pos\app\Controllers\utama.php(32): App\Models\login_m->index()
#7 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\utama->login()
#8 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
#9 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\pos\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next mysqli_sql_exception: MySQL server has gone away in D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'pos', 5432, '', 0)
#1 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\pos\app\Models\login_m.php(53): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\pos\app\Controllers\utama.php(32): App\Models\login_m->index()
#6 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\utama->login()
#7 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
#8 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\pos\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: MySQL server has gone away in D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\pos\app\Models\login_m.php(53): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\pos\app\Controllers\utama.php(32): App\Models\login_m->index()
#5 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\utama->login()
#6 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
#7 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\pos\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-12-11 20:11:24 --> Unable to connect to the database.
Main connection [MySQLi]: MySQL server has gone away
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user`
LEFT JOIN `contact` ON `contact`.`contact_id`=`user`.`contact_id`
LEFT JOIN `branch` ON `branch`.`branch_id`=`user`.`branch_id`
LEFT JOIN `permission_group` ON `permission_group`.`permission_group_id`=`user`.`permission_group_id`
LEFT JOIN `permission` ON `permission`.`permission_group_id`=`user`.`permission_group_id`
LEFT JOIN `modul` ON `modul`.`modul_id`=`permission`.`modul_id`
LEFT JOIN `modul_group` ON `modul_group`.`modul_group_id`=`modul`.`modul_group_id`
WHERE `username` = :username:
AND   (
`modul_group_name` = :modul_group_name:
OR `modul_group_name` = :modul_group_name.1:
OR `modul_group_name` = :modul_group_name.2:
OR `modul_group_name` = :modul_group_name.3:
OR `modul_group_name` = :modul_group_name.4:
OR `modul_group_name` = :modul_group_name.5:
OR `modul_group_name` = :modul_group_name.6:
OR `modul_group_name` = :modul_group_name.7:
OR `modul_group_name` = :modul_group_name.8:
 )', [...], false)
 3 APPPATH\Models\login_m.php(53): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\utama.php(32): App\Models\login_m->index()
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\utama->login()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-11 20:14:11 --> Error connecting to the database: ErrorException: mysqli::real_connect(): Error while reading greeting packet. PID=27876 in D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'D:\\xampp\\htdocs...', 171)
#1 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'pos', 5432, '', 0)
#2 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#4 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 D:\xampp\htdocs\pos\app\Models\login_m.php(53): CodeIgniter\Database\BaseBuilder->get()
#6 D:\xampp\htdocs\pos\app\Controllers\utama.php(32): App\Models\login_m->index()
#7 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\utama->login()
#8 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
#9 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\pos\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next mysqli_sql_exception: MySQL server has gone away in D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'pos', 5432, '', 0)
#1 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\pos\app\Models\login_m.php(53): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\pos\app\Controllers\utama.php(32): App\Models\login_m->index()
#6 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\utama->login()
#7 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
#8 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\pos\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: MySQL server has gone away in D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\pos\app\Models\login_m.php(53): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\pos\app\Controllers\utama.php(32): App\Models\login_m->index()
#5 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\utama->login()
#6 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
#7 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\pos\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-12-11 20:14:11 --> Unable to connect to the database.
Main connection [MySQLi]: MySQL server has gone away
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user`
LEFT JOIN `contact` ON `contact`.`contact_id`=`user`.`contact_id`
LEFT JOIN `branch` ON `branch`.`branch_id`=`user`.`branch_id`
LEFT JOIN `permission_group` ON `permission_group`.`permission_group_id`=`user`.`permission_group_id`
LEFT JOIN `permission` ON `permission`.`permission_group_id`=`user`.`permission_group_id`
LEFT JOIN `modul` ON `modul`.`modul_id`=`permission`.`modul_id`
LEFT JOIN `modul_group` ON `modul_group`.`modul_group_id`=`modul`.`modul_group_id`
WHERE `username` = :username:
AND   (
`modul_group_name` = :modul_group_name:
OR `modul_group_name` = :modul_group_name.1:
OR `modul_group_name` = :modul_group_name.2:
OR `modul_group_name` = :modul_group_name.3:
OR `modul_group_name` = :modul_group_name.4:
OR `modul_group_name` = :modul_group_name.5:
OR `modul_group_name` = :modul_group_name.6:
OR `modul_group_name` = :modul_group_name.7:
OR `modul_group_name` = :modul_group_name.8:
 )', [...], false)
 3 APPPATH\Models\login_m.php(53): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\utama.php(32): App\Models\login_m->index()
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\utama->login()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-11 20:17:38 --> akunting is not a valid database connection group.
in SYSTEMPATH\Database\Config.php on line 70.
 1 APPPATH\Controllers\baseController.php(57): CodeIgniter\Database\Config::connect('akunting')
 2 SYSTEMPATH\CodeIgniter.php(890): App\Controllers\baseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
 3 SYSTEMPATH\CodeIgniter.php(473): CodeIgniter\CodeIgniter->createController()
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-11 20:17:42 --> akunting is not a valid database connection group.
in SYSTEMPATH\Database\Config.php on line 70.
 1 APPPATH\Controllers\baseController.php(57): CodeIgniter\Database\Config::connect('akunting')
 2 SYSTEMPATH\CodeIgniter.php(890): App\Controllers\baseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
 3 SYSTEMPATH\CodeIgniter.php(473): CodeIgniter\CodeIgniter->createController()
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-11 21:04:35 --> akunting is not a valid database connection group.
in SYSTEMPATH\Database\Config.php on line 70.
 1 APPPATH\Controllers\baseController.php(57): CodeIgniter\Database\Config::connect('akunting')
 2 SYSTEMPATH\CodeIgniter.php(890): App\Controllers\baseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
 3 SYSTEMPATH\CodeIgniter.php(473): CodeIgniter\CodeIgniter->createController()
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-11 21:05:32 --> akunting is not a valid database connection group.
in SYSTEMPATH\Database\Config.php on line 70.
 1 APPPATH\Controllers\baseController.php(57): CodeIgniter\Database\Config::connect('akunting')
 2 SYSTEMPATH\CodeIgniter.php(890): App\Controllers\baseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
 3 SYSTEMPATH\CodeIgniter.php(473): CodeIgniter\CodeIgniter->createController()
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-11 21:08:18 --> syntax error, unexpected token "->"
in APPPATH\Models\login_m.php on line 22.
 1 SYSTEMPATH\Autoloader\Autoloader.php(259): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH\\Models\\login_m.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(237): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\login_m')
 3 APPPATH\Controllers\utama.php(31): CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\login_m')
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\utama->login()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-11 21:09:17 --> akunting is not a valid database connection group.
in SYSTEMPATH\Database\Config.php on line 70.
 1 APPPATH\Models\core_m.php(25): CodeIgniter\Database\Config::connect('akunting')
 2 APPPATH\Controllers\utama.php(31): App\Models\Core_m->__construct()
 3 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\utama->login()
 4 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
 5 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-11 21:23:24 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'YOUR QUERY HERE' at line 1 in D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('YOUR QUERY HERE', 0)
#1 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('YOUR QUERY HERE')
#2 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('YOUR QUERY HERE')
#3 D:\xampp\htdocs\pos\app\Models\login_m.php(30): CodeIgniter\Database\BaseConnection->query('YOUR QUERY HERE')
#4 D:\xampp\htdocs\pos\app\Controllers\utama.php(32): App\Models\login_m->index()
#5 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\utama->login()
#6 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
#7 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\pos\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-12-11 21:23:24 --> You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'YOUR QUERY HERE' at line 1
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('YOUR QUERY HERE', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('YOUR QUERY HERE')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('YOUR QUERY HERE')
 4 APPPATH\Models\login_m.php(30): CodeIgniter\Database\BaseConnection->query('YOUR QUERY HERE')
 5 APPPATH\Controllers\utama.php(32): App\Models\login_m->index()
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\utama->login()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-11 21:23:43 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '[Current Database]' at line 1 in D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT DB_NAME(...', 0)
#1 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT DB_NAME(...')
#2 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT DB_NAME(...')
#3 D:\xampp\htdocs\pos\app\Models\login_m.php(30): CodeIgniter\Database\BaseConnection->query('SELECT DB_NAME(...')
#4 D:\xampp\htdocs\pos\app\Controllers\utama.php(32): App\Models\login_m->index()
#5 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\utama->login()
#6 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
#7 D:\xampp\htdocs\pos\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\pos\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-12-11 21:23:43 --> You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '[Current Database]' at line 1
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('SELECT DB_NAME() AS [Current Database]', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT DB_NAME() AS [Current Database]')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT DB_NAME() AS [Current Database]')
 4 APPPATH\Models\login_m.php(30): CodeIgniter\Database\BaseConnection->query('SELECT DB_NAME() AS [Current Database]')
 5 APPPATH\Controllers\utama.php(32): App\Models\login_m->index()
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\utama->login()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-11 21:34:07 --> Undefined variable $db
in APPPATH\Models\login_m.php on line 31.
 1 APPPATH\Models\login_m.php(31): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $db', 'APPPATH\\Models\\login_m.php', 31)
 2 APPPATH\Controllers\utama.php(32): App\Models\login_m->index()
 3 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\utama->login()
 4 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
 5 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-11 21:35:46 --> Call to undefined method CodeIgniter\Database\MySQLi\Result::countAll()
in APPPATH\Models\login_m.php on line 34.
 1 APPPATH\Controllers\utama.php(32): App\Models\login_m->index()
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\utama->login()
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-11 21:38:25 --> Call to undefined method CodeIgniter\Database\MySQLi\Result::countAll()
in APPPATH\Models\login_m.php on line 33.
 1 APPPATH\Controllers\utama.php(32): App\Models\login_m->index()
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\utama->login()
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-11 21:39:34 --> Call to undefined method CodeIgniter\Database\MySQLi\Builder::getNumRows()
in APPPATH\Models\login_m.php on line 34.
 1 APPPATH\Controllers\utama.php(32): App\Models\login_m->index()
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\utama->login()
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-11 21:42:27 --> syntax error, unexpected identifier "ihsan", expecting ")"
in APPPATH\Models\login_m.php on line 35.
 1 SYSTEMPATH\Autoloader\Autoloader.php(259): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH\\Models\\login_m.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(237): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\login_m')
 3 APPPATH\Controllers\utama.php(31): CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\login_m')
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\utama->login()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-11 21:48:32 --> Undefined property: stdClass::$user_id
in APPPATH\Models\login_m.php on line 48.
 1 APPPATH\Models\login_m.php(48): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: stdClass::$user_id', 'APPPATH\\Models\\login_m.php', 48)
 2 APPPATH\Controllers\utama.php(32): App\Models\login_m->index()
 3 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\utama->login()
 4 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
 5 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-11 21:49:24 --> akunting is not a valid database connection group.
in SYSTEMPATH\Database\Config.php on line 70.
 1 APPPATH\Views\template\header_v.php(8): CodeIgniter\Database\Config::connect('akunting')
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\template\\header_v.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\View\View.php(431): CodeIgniter\View\View->render('template/header_v', null, true)
 5 APPPATH\Views\utama_v.php(11): CodeIgniter\View\View->include('template/header_v')
 6 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\utama_v.php')
 7 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 8 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('utama_v', [], true)
 9 APPPATH\Controllers\utama.php(19): view('utama_v')
10 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\utama->index()
11 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
12 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-11 21:49:48 --> Undefined property: CodeIgniter\View\View::$akunting
in APPPATH\Views\utama_v.php on line 60.
 1 APPPATH\Views\utama_v.php(60): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: CodeIgniter\\View\\View::$akunting', 'APPPATH\\Views\\utama_v.php', 60)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\utama_v.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('utama_v', [], true)
 5 APPPATH\Controllers\utama.php(19): view('utama_v')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\utama->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-11 21:51:03 --> Maximum execution time of 120 seconds exceeded
in SYSTEMPATH\Debug\Exceptions.php on line 153.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2022-12-11 11:56:59 --> The namespace delimiter is a backslash (\), not a slash (/). Route handler: \App\Controllers\master/mjabatan::index
in SYSTEMPATH\Router\Router.php on line 466.
 1 SYSTEMPATH\Router\Router.php(466): CodeIgniter\Router\Exceptions\RouterException::forInvalidControllerName('\\App\\Controllers\\master/mjabatan::index')
 2 SYSTEMPATH\Router\Router.php(181): CodeIgniter\Router\Router->checkRoutes('mjabatan')
 3 SYSTEMPATH\CodeIgniter.php(802): CodeIgniter\Router\Router->handle('mjabatan')
 4 SYSTEMPATH\CodeIgniter.php(430): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 5 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-11 12:00:08 --> The namespace delimiter is a backslash (\), not a slash (/). Route handler: \App\Controllers\master/mposition::index
in SYSTEMPATH\Router\Router.php on line 466.
 1 SYSTEMPATH\Router\Router.php(466): CodeIgniter\Router\Exceptions\RouterException::forInvalidControllerName('\\App\\Controllers\\master/mposition::index')
 2 SYSTEMPATH\Router\Router.php(181): CodeIgniter\Router\Router->checkRoutes('mposition')
 3 SYSTEMPATH\CodeIgniter.php(802): CodeIgniter\Router\Router->handle('mposition')
 4 SYSTEMPATH\CodeIgniter.php(430): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 5 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-11 15:03:40 --> The namespace delimiter is a backslash (\), not a slash (/). Route handler: \App\Controllers\master/makses::index
in SYSTEMPATH\Router\Router.php on line 466.
 1 SYSTEMPATH\Router\Router.php(466): CodeIgniter\Router\Exceptions\RouterException::forInvalidControllerName('\\App\\Controllers\\master/makses::index')
 2 SYSTEMPATH\Router\Router.php(181): CodeIgniter\Router\Router->checkRoutes('makses')
 3 SYSTEMPATH\CodeIgniter.php(802): CodeIgniter\Router\Router->handle('makses')
 4 SYSTEMPATH\CodeIgniter.php(430): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 5 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-11 16:42:16 --> The namespace delimiter is a backslash (\), not a slash (/). Route handler: \App\Controllers\master/muser::index
in SYSTEMPATH\Router\Router.php on line 466.
 1 SYSTEMPATH\Router\Router.php(466): CodeIgniter\Router\Exceptions\RouterException::forInvalidControllerName('\\App\\Controllers\\master/muser::index')
 2 SYSTEMPATH\Router\Router.php(181): CodeIgniter\Router\Router->checkRoutes('muser')
 3 SYSTEMPATH\CodeIgniter.php(802): CodeIgniter\Router\Router->handle('muser')
 4 SYSTEMPATH\CodeIgniter.php(430): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 5 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-11 17:57:16 --> The namespace delimiter is a backslash (\), not a slash (/). Route handler: \App\Controllers\master/muser::index
in SYSTEMPATH\Router\Router.php on line 466.
 1 SYSTEMPATH\Router\Router.php(466): CodeIgniter\Router\Exceptions\RouterException::forInvalidControllerName('\\App\\Controllers\\master/muser::index')
 2 SYSTEMPATH\Router\Router.php(181): CodeIgniter\Router\Router->checkRoutes('muser')
 3 SYSTEMPATH\CodeIgniter.php(802): CodeIgniter\Router\Router->handle('muser')
 4 SYSTEMPATH\CodeIgniter.php(430): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 5 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-11 19:17:03 --> The namespace delimiter is a backslash (\), not a slash (/). Route handler: \App\Controllers\master/mpassword::index
in SYSTEMPATH\Router\Router.php on line 466.
 1 SYSTEMPATH\Router\Router.php(466): CodeIgniter\Router\Exceptions\RouterException::forInvalidControllerName('\\App\\Controllers\\master/mpassword::index')
 2 SYSTEMPATH\Router\Router.php(181): CodeIgniter\Router\Router->checkRoutes('mpassword')
 3 SYSTEMPATH\CodeIgniter.php(802): CodeIgniter\Router\Router->handle('mpassword')
 4 SYSTEMPATH\CodeIgniter.php(430): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 5 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
